import type { Metadata } from "next";
import "./globals.css";
// import { geistSans, geistMono } from 'some-module'; // Comment out or remove this line if not needed

export const metadata: Metadata = {
  title: "Reservation System",
  description: "Generated by ntsiakiris",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
